/*
 * CareBar.java
 *
 * Created on __DATE__, __TIME__
 */

package jiemian;

/**
 *
 * @author  __USER__
 */
public class CareBar extends javax.swing.JFrame {

	/** Creates new form CareBar */
	public CareBar() {
		initComponents();
		this.setLocationRelativeTo(null);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		imageJpanel1 = new jiemian.ImageJpanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		jButton7 = new javax.swing.JButton();
		jButton8 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		imageJpanel1.setBackground(new java.awt.Color(255, 255, 255));

		jLabel1.setBackground(new java.awt.Color(255, 255, 255));
		jLabel1.setFont(new java.awt.Font("²Ö¶úÐ¡ÂþÂþÌå W02", 1, 42));
		jLabel1.setText("\u5173\u6ce8\u7684\u5427");

		jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/changguangbar.jpg"))); // NOI18N

		jLabel3.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));
		jLabel3.setForeground(new java.awt.Color(0, 204, 204));
		jLabel3.setText("\u6211\u5173\u6ce8\u7684\u5427");

		jButton1.setBackground(new java.awt.Color(255, 255, 255));
		jButton1.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));
		jButton1.setText("\u827e\u5c14\u4e4b\u5149     12\u7ea7");
		jButton1.setBorder(null);

		jButton2.setBackground(new java.awt.Color(255, 255, 255));
		jButton2.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));
		jButton2
				.setText("\u827e\u5c14\u4e4b\u5149\u4ea4\u6613          11\u7ea7");
		jButton2.setBorder(null);

		jButton3.setBackground(new java.awt.Color(255, 255, 255));
		jButton3.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));
		jButton3.setText("300\u82f1\u96c4     11\u7ea7");
		jButton3.setBorder(null);

		jButton4.setBackground(new java.awt.Color(255, 255, 255));
		jButton4.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));
		jButton4
				.setText("\u4e2d\u5c71\u5927\u5b66\u5357\u65b9\u5b66\u9662   11\u7ea7");
		jButton4.setBorder(null);

		jButton5.setBackground(new java.awt.Color(255, 255, 255));
		jButton5.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));
		jButton5.setText("closers       11\u7ea7");
		jButton5.setBorder(null);

		jButton6.setBackground(new java.awt.Color(255, 255, 255));
		jButton6.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));
		jButton6.setText("\u9006\u6c34\u5bd2ol                  8\u7ea7");
		jButton6.setBorder(null);

		jButton7.setBackground(new java.awt.Color(255, 255, 255));
		jButton7.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));
		jButton7.setText("Java           8\u7ea7");
		jButton7.setBorder(null);

		jButton8.setBackground(new java.awt.Color(255, 255, 255));
		jButton8.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));
		jButton8.setText("dnf\u6218\u6597\u6cd5\u5e08            8\u7ea7");
		jButton8.setBorder(null);

		javax.swing.GroupLayout imageJpanel1Layout = new javax.swing.GroupLayout(
				imageJpanel1);
		imageJpanel1.setLayout(imageJpanel1Layout);
		imageJpanel1Layout.setHorizontalGroup(imageJpanel1Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						imageJpanel1Layout.createSequentialGroup().addGap(166,
								166, 166).addComponent(jLabel1)
								.addContainerGap(181, Short.MAX_VALUE))
				.addComponent(jLabel2,
						javax.swing.GroupLayout.Alignment.TRAILING,
						javax.swing.GroupLayout.DEFAULT_SIZE, 523,
						Short.MAX_VALUE).addGroup(
						imageJpanel1Layout.createSequentialGroup()
								.addContainerGap().addComponent(jLabel3)
								.addContainerGap(418, Short.MAX_VALUE))
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						imageJpanel1Layout.createSequentialGroup()
								.addContainerGap().addComponent(jButton1,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										228, Short.MAX_VALUE)
								.addGap(31, 31, 31).addComponent(jButton2,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										234,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap()).addGroup(
						imageJpanel1Layout.createSequentialGroup()
								.addContainerGap().addComponent(jButton3,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										228, Short.MAX_VALUE)
								.addGap(31, 31, 31).addComponent(jButton4,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										234,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap()).addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						imageJpanel1Layout.createSequentialGroup()
								.addContainerGap().addComponent(jButton5,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										228, Short.MAX_VALUE)
								.addGap(31, 31, 31).addComponent(jButton6,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										234,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap()).addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						imageJpanel1Layout.createSequentialGroup()
								.addContainerGap().addComponent(jButton7,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										228, Short.MAX_VALUE)
								.addGap(31, 31, 31).addComponent(jButton8,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										234,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap()));
		imageJpanel1Layout
				.setVerticalGroup(imageJpanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								imageJpanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel1)
										.addGap(35, 35, 35)
										.addComponent(
												jLabel2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												137,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel3)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												imageJpanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jButton1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																53,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																53,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												imageJpanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jButton3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																53,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																53,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												imageJpanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jButton5,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																53,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton6,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																53,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												imageJpanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jButton7,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																53,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton8,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																53,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(30, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				imageJpanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				imageJpanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new CareBar().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private jiemian.ImageJpanel imageJpanel1;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	// End of variables declaration//GEN-END:variables

}