/*
 * GM_Frame.java
 *
 * Created on __DATE__, __TIME__
 */

package jiemian;

import java.io.File;
import java.sql.SQLException;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

//import database.GM_data;
import database.ModelFactory;

/**
 *
 * @author  __USER__
 */
public class GM_Frame extends javax.swing.JFrame {
//	private GM_data gm;
//
//	/** Creates new form GM_Frame */
//	public GM_Frame(GM_data gm) {
//		this.gm = gm;
//		initComponents();
//		this.setLocationRelativeTo(null);
//	}
//
//	public GM_Frame() {
//		initComponents();
//		this.setLocationRelativeTo(null);
//	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		imageJpanel1 = new jiemian.ImageJpanel();
		jLabel3 = new javax.swing.JLabel();
		jTabbedPane1 = new javax.swing.JTabbedPane();
		imageJpanel2 = new jiemian.ImageJpanel();
		jButton12 = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();
		imageJpanel3 = new jiemian.ImageJpanel();
		jPanel8 = new javax.swing.JPanel();
		jLabel9 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		jButton9 = new javax.swing.JButton();
		jButton11 = new javax.swing.JButton();
		imageJpanel4 = new jiemian.ImageJpanel();
		jPanel6 = new javax.swing.JPanel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jButton8 = new javax.swing.JButton();
		jPanel7 = new javax.swing.JPanel();
		jLabel10 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jButton10 = new javax.swing.JButton();

		jLabel1.setText("jLabel1");

		jButton1.setText("jButton1");

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setIconImage(new ImageIcon("./src/img/8.gif").getImage());

		imageJpanel1.setImage(new ImageIcon("RBQ.jpg").getImage());

		jLabel3.setFont(new java.awt.Font("∫∫“«◊€“’ÃÂºÚ", 0, 48));
		jLabel3.setForeground(new java.awt.Color(255, 255, 255));
		jLabel3.setText("\u6b22\u8fceGM\uff1atrani\u4f7f\u7528");

		imageJpanel2.setBackground(new java.awt.Color(153, 255, 255));

		jButton12.setText("\u70b9\u6211");
		jButton12.setToolTipText("\u70b9\u51fb\u66f4\u6362\u5934\u50cf");
		jButton12.setBorder(null);
		jButton12.setContentAreaFilled(false);
		jButton12.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton12ActionPerformed(evt);
			}
		});

		jLabel4.setFont(new java.awt.Font("∫∫“«◊€“’ÃÂºÚ", 0, 24));
		jLabel4.setForeground(new java.awt.Color(255, 255, 255));
		jLabel4
				.setText("\u70b9\u51fb\u6309\u94ae\u4e0a\u4f20\u65b0\u7684\u82f1\u96c4\u5361\u7247\u7d20\u6750");

		javax.swing.GroupLayout imageJpanel2Layout = new javax.swing.GroupLayout(
				imageJpanel2);
		imageJpanel2.setLayout(imageJpanel2Layout);
		imageJpanel2Layout
				.setHorizontalGroup(imageJpanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								imageJpanel2Layout
										.createSequentialGroup()
										.addGroup(
												imageJpanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																imageJpanel2Layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				jLabel4))
														.addGroup(
																imageJpanel2Layout
																		.createSequentialGroup()
																		.addGap(
																				373,
																				373,
																				373)
																		.addComponent(
																				jButton12,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				215,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(414, Short.MAX_VALUE)));
		imageJpanel2Layout.setVerticalGroup(imageJpanel2Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						imageJpanel2Layout.createSequentialGroup().addGap(33,
								33, 33).addComponent(jLabel4)
								.addGap(83, 83, 83).addComponent(jButton12,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										259,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(110, Short.MAX_VALUE)));

		jTabbedPane1.addTab("\u66f4\u65b0\u5361\u724c", imageJpanel2);

		jPanel8.setBackground(new java.awt.Color(40, 52, 59));

		jLabel9.setFont(new java.awt.Font("Œ¢»Ì—≈∫⁄", 1, 24));
		jLabel9.setForeground(new java.awt.Color(255, 255, 255));
		jLabel9
				.setText("\u8bf7\u5728\u4e0b\u65b9\u8f93\u5165\u60a8\u9700\u8981\u53d1\u5e03\u7684\u516c\u544a");

		jLabel11.setFont(new java.awt.Font("Œ¢»Ì—≈∫⁄", 1, 24));
		jLabel11.setForeground(new java.awt.Color(255, 255, 255));
		jLabel11
				.setText("\u516c\u544a\u5c06\u4f1a\u53d1\u9001\u81f3\u6240\u6709\u6b63\u5e38\u6e38\u620f\u7684\u7528\u6237");

		jTextField3.setBackground(new java.awt.Color(0, 204, 204));
		jTextField3.setFont(new java.awt.Font("Œ¢»Ì—≈∫⁄", 1, 18));
		jTextField3.setForeground(new java.awt.Color(0, 153, 153));

		jButton9.setBackground(new java.awt.Color(0, 204, 204));
		jButton9.setFont(new java.awt.Font("Œ¢»Ì—≈∫⁄", 1, 18));
		jButton9.setForeground(new java.awt.Color(0, 102, 102));
		jButton9.setText("\u786e\u5b9a");
//		jButton9.addActionListener(new java.awt.event.ActionListener() {
//			public void actionPerformed(java.awt.event.ActionEvent evt) {
//				jButton9ActionPerformed(evt);
//			}
//		});

		jButton11.setBackground(new java.awt.Color(0, 204, 204));
		jButton11.setFont(new java.awt.Font("Œ¢»Ì—≈∫⁄", 1, 18));
		jButton11.setForeground(new java.awt.Color(0, 102, 102));
		jButton11.setText("\u6e05\u7a7a");
		jButton11.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton11ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(
				jPanel8);
		jPanel8.setLayout(jPanel8Layout);
		jPanel8Layout
				.setHorizontalGroup(jPanel8Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel8Layout
										.createSequentialGroup()
										.addGroup(
												jPanel8Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel8Layout
																		.createSequentialGroup()
																		.addGap(
																				147,
																				147,
																				147)
																		.addGroup(
																				jPanel8Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addGroup(
																								jPanel8Layout
																										.createSequentialGroup()
																										.addComponent(
																												jButton11,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												84,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jButton9,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												84,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addComponent(
																								jTextField3,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								682,
																								javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addGroup(
																jPanel8Layout
																		.createSequentialGroup()
																		.addGap(
																				269,
																				269,
																				269)
																		.addComponent(
																				jLabel11,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				441,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel8Layout
																		.createSequentialGroup()
																		.addGap(
																				293,
																				293,
																				293)
																		.addComponent(
																				jLabel9)))
										.addContainerGap(173, Short.MAX_VALUE)));
		jPanel8Layout
				.setVerticalGroup(jPanel8Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel8Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												jLabel9,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												42,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jLabel11,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												47,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(
												jTextField3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												249,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addGroup(
												jPanel8Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jButton9,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																36,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton11,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																36,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(75, Short.MAX_VALUE)));

		javax.swing.GroupLayout imageJpanel3Layout = new javax.swing.GroupLayout(
				imageJpanel3);
		imageJpanel3.setLayout(imageJpanel3Layout);
		imageJpanel3Layout.setHorizontalGroup(imageJpanel3Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		imageJpanel3Layout.setVerticalGroup(imageJpanel3Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE,
						510, Short.MAX_VALUE));

		jTabbedPane1.addTab("\u516c\u544a\u53d1\u5e03", imageJpanel3);

		imageJpanel4.setBackground(new java.awt.Color(153, 255, 255));

		jPanel6.setBackground(new java.awt.Color(40, 52, 59));

		jLabel7.setFont(new java.awt.Font("Œ¢»Ì—≈∫⁄", 1, 24));
		jLabel7.setForeground(new java.awt.Color(255, 255, 255));
		jLabel7.setText("\u901a\u8fc7\u8f93\u5165\u7528\u6237\u7684ID");

		jLabel8.setFont(new java.awt.Font("Œ¢»Ì—≈∫⁄", 1, 24));
		jLabel8.setForeground(new java.awt.Color(255, 255, 255));
		jLabel8
				.setText("\u53ef\u5bf9\u7528\u6237\u8fdb\u884c\u65e0\u671f\u9650\u5c01\u7981");

		jTextField1.setBackground(new java.awt.Color(0, 204, 204));
		jTextField1.setFont(new java.awt.Font("Œ¢»Ì—≈∫⁄", 1, 18));
		jTextField1.setForeground(new java.awt.Color(0, 153, 153));
		jTextField1.setText("\u60f3\u8981\u641c\u7d22\u7684\u7528\u6237ID");
		jTextField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});

		jButton8.setBackground(new java.awt.Color(0, 204, 204));
		jButton8.setFont(new java.awt.Font("Œ¢»Ì—≈∫⁄", 1, 18));
		jButton8.setForeground(new java.awt.Color(0, 102, 102));
		jButton8.setText("\u786e\u5b9a");
//		jButton8.addActionListener(new java.awt.event.ActionListener() {
//			public void actionPerformed(java.awt.event.ActionEvent evt) {
//				jButton8ActionPerformed(evt);
//			}
//		});

		javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(
				jPanel6);
		jPanel6.setLayout(jPanel6Layout);
		jPanel6Layout
				.setHorizontalGroup(jPanel6Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel6Layout
										.createSequentialGroup()
										.addGap(147, 147, 147)
										.addComponent(
												jTextField1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												388,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												42, Short.MAX_VALUE)
										.addComponent(
												jButton8,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												84,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(47, 47, 47))
						.addGroup(
								jPanel6Layout.createSequentialGroup().addGap(
										245, 245, 245).addComponent(jLabel7,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										210,
										javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(253, Short.MAX_VALUE))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel6Layout
										.createSequentialGroup()
										.addContainerGap(204, Short.MAX_VALUE)
										.addComponent(
												jLabel8,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												351,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(153, 153, 153)));
		jPanel6Layout
				.setVerticalGroup(jPanel6Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel6Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												jLabel7,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												42,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jLabel8,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												47,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addGroup(
												jPanel6Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jTextField1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																40,
																Short.MAX_VALUE)
														.addComponent(
																jButton8,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																36,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(49, Short.MAX_VALUE)));

		jLabel10.setFont(new java.awt.Font("Œ¢»Ì—≈∫⁄", 1, 24));
		jLabel10.setText("\u8f93\u5165\u7528\u6237ID\u8fdb\u884c\u89e3\u5c01");

		jTextField2.setBackground(new java.awt.Color(0, 255, 255));
		jTextField2.setFont(new java.awt.Font("Œ¢»Ì—≈∫⁄", 1, 18));
		jTextField2.setText("\u73a9\u5bb6xxx");
		jTextField2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField2ActionPerformed(evt);
			}
		});

		jButton10.setBackground(new java.awt.Color(0, 204, 204));
		jButton10.setFont(new java.awt.Font("Œ¢»Ì—≈∫⁄", 1, 18));
		jButton10.setForeground(new java.awt.Color(0, 102, 102));
		jButton10.setText("\u786e\u5b9a");
//		jButton10.addActionListener(new java.awt.event.ActionListener() {
//			public void actionPerformed(java.awt.event.ActionEvent evt) {
//				jButton10ActionPerformed(evt);
//			}
//		});

		javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(
				jPanel7);
		jPanel7.setLayout(jPanel7Layout);
		jPanel7Layout
				.setHorizontalGroup(jPanel7Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel7Layout
										.createSequentialGroup()
										.addGroup(
												jPanel7Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel7Layout
																		.createSequentialGroup()
																		.addGap(
																				153,
																				153,
																				153)
																		.addComponent(
																				jTextField2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				384,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel7Layout
																		.createSequentialGroup()
																		.addGap(
																				298,
																				298,
																				298)
																		.addComponent(
																				jButton10,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				84,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel7Layout
																		.createSequentialGroup()
																		.addGap(
																				239,
																				239,
																				239)
																		.addComponent(
																				jLabel10)))
										.addContainerGap(171, Short.MAX_VALUE)));
		jPanel7Layout
				.setVerticalGroup(jPanel7Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel7Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												jLabel10,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												42,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(
												jTextField2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												44,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												jButton10,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												36,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(26, Short.MAX_VALUE)));

		javax.swing.GroupLayout imageJpanel4Layout = new javax.swing.GroupLayout(
				imageJpanel4);
		imageJpanel4.setLayout(imageJpanel4Layout);
		imageJpanel4Layout
				.setHorizontalGroup(imageJpanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								imageJpanel4Layout
										.createSequentialGroup()
										.addGap(144, 144, 144)
										.addGroup(
												imageJpanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jPanel7,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jPanel6,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(150, Short.MAX_VALUE)));
		imageJpanel4Layout
				.setVerticalGroup(imageJpanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								imageJpanel4Layout
										.createSequentialGroup()
										.addGap(31, 31, 31)
										.addComponent(
												jPanel6,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												221,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												44, Short.MAX_VALUE)
										.addComponent(
												jPanel7,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap()));

		jTabbedPane1.addTab("\u7528\u6237\u5c01\u7981", imageJpanel4);

		javax.swing.GroupLayout imageJpanel1Layout = new javax.swing.GroupLayout(
				imageJpanel1);
		imageJpanel1.setLayout(imageJpanel1Layout);
		imageJpanel1Layout
				.setHorizontalGroup(imageJpanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								imageJpanel1Layout
										.createSequentialGroup()
										.addGroup(
												imageJpanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																imageJpanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				291,
																				291,
																				291)
																		.addComponent(
																				jLabel3))
														.addGroup(
																imageJpanel1Layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				jTabbedPane1,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				1007,
																				Short.MAX_VALUE)))
										.addContainerGap()));
		imageJpanel1Layout
				.setVerticalGroup(imageJpanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								imageJpanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel3)
										.addGap(18, 18, 18)
										.addComponent(
												jTabbedPane1,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												542, Short.MAX_VALUE)
										.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				imageJpanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				imageJpanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

//	private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {
//		// TODO add your handling code here:
//		try {
//			ModelFactory.deblockingPlayer(this.jTextField2.getText());
//		} catch (SQLException e) {
//			// TODO Auto-generated catch block
//			e.printStackTrace();
//		} catch (ClassNotFoundException e) {
//			// TODO Auto-generated catch block
//			e.printStackTrace();
//		}
//	}
//
//	private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {
//		// TODO add your handling code here:
//		try {
//
//			ModelFactory.deletePlayer(this.jTextField1.getText());
//		} catch (SQLException e) {
//			// TODO Auto-generated catch block
//			e.printStackTrace();
//		} catch (ClassNotFoundException e) {
//			// TODO Auto-generated catch block
//			e.printStackTrace();
//		}
//	}

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		jTextField1.setText("");
	}

	private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		jTextField2.setText("");
	}

//	private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {
//		// TODO add your handling code here:
//		String message = this.jTextField3.getText();
//		try {
//			ModelFactory.sendAnnouncement(gm.getName(), message);
//		} catch (SQLException e) {
//			// TODO Auto-generated catch block
//			e.printStackTrace();
//		} catch (ClassNotFoundException e) {
//			// TODO Auto-generated catch block
//			e.printStackTrace();
//		}
//	}

	private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.jTextField3.setText("");
	}

	private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {
		JFileChooser jfc = new JFileChooser();
		jfc.showOpenDialog(this);
		File f = jfc.getSelectedFile();
		this.jButton9.setIcon(new ImageIcon(f.getAbsolutePath()));
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		try {
			org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper.launchBeautyEyeLNF();
		} catch (Exception e) {
			//TODO exception
		}
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new GM_Frame().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private jiemian.ImageJpanel imageJpanel1;
	private jiemian.ImageJpanel imageJpanel2;
	private jiemian.ImageJpanel imageJpanel3;
	private jiemian.ImageJpanel imageJpanel4;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton10;
	private javax.swing.JButton jButton11;
	private javax.swing.JButton jButton12;
	private javax.swing.JButton jButton8;
	private javax.swing.JButton jButton9;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JPanel jPanel8;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	// End of variables declaration//GEN-END:variables

}