/*
 * Resgister.java
 *
 * Created on __DATE__, __TIME__
 */

package jiemian;

import java.sql.SQLException;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import database.ModelFactory;
import database.Users;

/**
 *
 * @author  __USER__
 */
public class Resgister extends javax.swing.JFrame {

	/** Creates new form Resgister */
	public Resgister() {
		initComponents();
		this.setLocationRelativeTo(null);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		imageJpanel1 = new jiemian.ImageJpanel();
		jTextField1 = new javax.swing.JTextField();
		jTextField2 = new javax.swing.JTextField();
		jPasswordField1 = new javax.swing.JPasswordField();
		jPasswordField2 = new javax.swing.JPasswordField();
		jButton1 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setIconImage(new ImageIcon("./src/img/resg.jpg").getImage());

		imageJpanel1.setImage(new ImageIcon("./src/img/resg.jpg").getImage());

		jTextField1.setFont(new java.awt.Font("≤÷∂˙ •µÆª∂∏ËÃÂ W05", 2, 24));
		jTextField1.setForeground(new java.awt.Color(0, 255, 204));
		jTextField1.setText("\u8f93\u5165\u60a8\u7684\u8d26\u53f7");
		jTextField1.setBorder(null);
		jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				zhclear(evt);
			}
		});

		jTextField2.setFont(new java.awt.Font("≤÷∂˙ •µÆª∂∏ËÃÂ W05", 2, 24));
		jTextField2.setForeground(new java.awt.Color(0, 255, 204));
		jTextField2.setText("\u8f93\u5165\u60a8\u7684\u6635\u79f0");
		jTextField2.setBorder(null);
		jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				jTextField2zhclear(evt);
			}
		});
		jTextField2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField2ActionPerformed(evt);
			}
		});

		jPasswordField1.setFont(new java.awt.Font("ÀŒÃÂ", 0, 24));
		jPasswordField1.setBorder(null);

		jPasswordField2.setFont(new java.awt.Font("ÀŒÃÂ", 0, 24));
		jPasswordField2.setBorder(null);

		jButton1.setFont(new java.awt.Font("“Â∆Ù÷–‘≤ÃÂ", 0, 36));
		jButton1.setForeground(new java.awt.Color(255, 255, 255));
		jButton1
				.setText("\u786e\u8ba4\u65e0\u8bef\uff0c\u63d0\u4ea4\u6ce8\u518c");
		jButton1.setBorder(null);
		jButton1.setContentAreaFilled(false);
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				
					jButton1ActionPerformed(evt);
				
			}
		});

		javax.swing.GroupLayout imageJpanel1Layout = new javax.swing.GroupLayout(
				imageJpanel1);
		imageJpanel1.setLayout(imageJpanel1Layout);
		imageJpanel1Layout
				.setHorizontalGroup(imageJpanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								imageJpanel1Layout
										.createSequentialGroup()
										.addGroup(
												imageJpanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																imageJpanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				73,
																				73,
																				73)
																		.addComponent(
																				jButton1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				492,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																imageJpanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				45,
																				45,
																				45)
																		.addGroup(
																				imageJpanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								jPasswordField2)
																						.addComponent(
																								jPasswordField1)
																						.addComponent(
																								jTextField1,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								549,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextField2,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								549,
																								Short.MAX_VALUE))))
										.addContainerGap(52, Short.MAX_VALUE)));
		imageJpanel1Layout
				.setVerticalGroup(imageJpanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								imageJpanel1Layout
										.createSequentialGroup()
										.addGap(283, 283, 283)
										.addComponent(
												jTextField1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												55,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(81, 81, 81)
										.addComponent(
												jTextField2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												55,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(74, 74, 74)
										.addComponent(
												jPasswordField1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												55,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(73, 73, 73)
										.addComponent(
												jPasswordField2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												55,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												54, Short.MAX_VALUE)
										.addComponent(
												jButton1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												77,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(38, 38, 38)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				imageJpanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				imageJpanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt){
		// TODO add your handling code here:
		String no = jTextField1.getText();
		String pw = String.valueOf(this.jPasswordField1.getPassword());
		String name = jTextField2.getText();
		String pw2 = String.valueOf(this.jPasswordField2.getPassword());
		if(pw.equals(pw2)){
			Users user;
			try {
				user = ModelFactory.register(no, pw, name);
				JOptionPane.showMessageDialog(this, "◊¢≤·≥…π¶£°");
				new MainBlank(user).setVisible(true);
				this.dispose();
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				JOptionPane.showMessageDialog(this, "∏√’À∫≈“—¥Ê‘⁄£°");
			} catch (ClassNotFoundException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
		}
		
	}

	private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jTextField2zhclear(java.awt.event.MouseEvent evt) {
		jTextField2.setText("");
	}

	private void zhclear(java.awt.event.MouseEvent evt) {
		jTextField1.setText("");
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Resgister().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private jiemian.ImageJpanel imageJpanel1;
	private javax.swing.JButton jButton1;
	private javax.swing.JPasswordField jPasswordField1;
	private javax.swing.JPasswordField jPasswordField2;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	// End of variables declaration//GEN-END:variables

}