/*
 * Show_tie.java
 *
 * Created on __DATE__, __TIME__
 */

package jiemian;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.SQLException;

import database.ModelFactory;
import database.Tip;
import database.Users;

/**
 *
 * @author  __USER__
 */
public class Show_tie extends javax.swing.JFrame {

	/** Creates new form Show_tie 
	 * @throws ClassNotFoundException 
	 * @throws SQLException */
	private Tip tip;
	private Users user;
	private database.Replay replay1;
	private database.Replay replay2;
	private database.Replay replay3;

	public Show_tie(Tip tip1, Users user2) throws SQLException,
			ClassNotFoundException {
		tip = tip1;
		user = user2;
		replay1 = ModelFactory.chaHuifu(ModelFactory.chaReplayIDMin(tip
				.getTipId()));
		replay3 = ModelFactory.chaHuifu(ModelFactory.chaReplayIDMax(tip
				.getTipId()));
		for (int i = ModelFactory.chaReplayIDMin(tip.getTipId()) + 1; i <= ModelFactory
				.chaReplayIDMax(tip.getTipId()); i++) {
			if (tip.getTipId() == ModelFactory.chaReplayTipID(i)) {
				replay2 = ModelFactory.chaHuifu(i);
			} else {
				replay2 = null;
			}
		}
		initComponents();
		this.jTextField3.setText(tip.getTipTitle());
		this.jTextArea1.setText(tip.getTipContext());

		if (replay1 != null) {
			this.jTextField4.setText(ModelFactory.chaWritor(replay1.getUsId()));
			this.jLabel3.setText(String.valueOf(ModelFactory.chaJifen(replay1
					.getUsId())));
			this.jTextArea2.setText(replay1.getRepContent());
		}
		if (replay2 != null) {
			this.jTextField5.setText(ModelFactory.chaWritor(replay2.getUsId()));
			this.jLabel5.setText(String.valueOf(ModelFactory.chaJifen(replay2
					.getUsId())));
			this.jTextArea3.setText(replay2.getRepContent());
		}
		if (replay3 != null) {
			this.jTextField6.setText(ModelFactory.chaWritor(replay3.getUsId()));
			this.jLabel7.setText(String.valueOf(ModelFactory.chaJifen(replay3
					.getUsId())));
			this.jTextArea4.setText(replay3.getRepContent());
		}

		this.setLocationRelativeTo(null);
	}

	public Show_tie() {
		initComponents();
		this.setLocationRelativeTo(null);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jTextField2 = new javax.swing.JTextField();
		jButton2 = new javax.swing.JButton();
		jTextField3 = new javax.swing.JTextField();
		jButton5 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		jSeparator1 = new javax.swing.JSeparator();
		jTextField4 = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jSeparator2 = new javax.swing.JSeparator();
		jScrollPane3 = new javax.swing.JScrollPane();
		jTextArea2 = new javax.swing.JTextArea();
		jSeparator3 = new javax.swing.JSeparator();
		jTextField5 = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jScrollPane4 = new javax.swing.JScrollPane();
		jTextArea3 = new javax.swing.JTextArea();
		jSeparator4 = new javax.swing.JSeparator();
		jTextField6 = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jScrollPane5 = new javax.swing.JScrollPane();
		jTextArea4 = new javax.swing.JTextArea();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jSeparator5 = new javax.swing.JSeparator();
		jLabel11 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));
		jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/tieba_logo.png"))); // NOI18N
		jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(
				20, 10, -1, -1));

		jTextField1.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 24));
		jTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
		jPanel1.add(jTextField1,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 530,
						50));

		jButton1.setBackground(new java.awt.Color(55, 133, 249));
		jButton1.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 20));
		jButton1.setForeground(new java.awt.Color(255, 255, 255));
		jButton1.setText("\u5168\u5427\u641c\u7d22");
		jButton1.setBorder(null);
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		jPanel1.add(jButton1,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 50, 110,
						50));

		jTextField2.setBackground(new java.awt.Color(244, 246, 249));
		jTextField2.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 15));
		jTextField2.setForeground(new java.awt.Color(0, 204, 204));
		jTextField2.setText("\u5171\u67093\u6761\u56de\u590d");
		jTextField2.setBorder(null);
		jPanel1.add(jTextField2,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 950,
						50));

		jButton2.setBackground(new java.awt.Color(244, 246, 249));
		jButton2.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 15));
		jButton2.setForeground(new java.awt.Color(0, 204, 204));
		jButton2.setText("<<\u8fd4\u56de\u4e3b\u754c\u9762");
		jButton2.setBorder(null);
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		jPanel1.add(jButton2,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 130,
						100, 50));

		jTextField3.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 24));
		jTextField3.setText("\u5e16\u5b50\u6807\u9898");
		jTextField3.setBorder(null);
		jTextField3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField3ActionPerformed(evt);
			}
		});
		jPanel1.add(jTextField3,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 750,
						70));

		jButton5.setBackground(new java.awt.Color(255, 255, 255));
		jButton5.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 15));
		jButton5.setText("\u56de\u590d");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});
		jPanel1.add(jButton5,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 200, 80,
						-1));

		jButton6.setBackground(new java.awt.Color(255, 255, 255));
		jButton6.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 15));
		jButton6.setText("\u5237\u65b0");
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});
		jPanel1.add(jButton6,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 200, 80,
						-1));

		jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
		jPanel1.add(jSeparator1,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 700, 1040,
						-1));

		jTextField4.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 15));
		jTextField4.setText("\u6682\u65e0");
		jTextField4.setBorder(null);
		jPanel1.add(jTextField4,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1,
						-1));

		jLabel2.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 15));
		jLabel2.setText("\u79ef\u5206\uff1a");
		jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(
				30, 500, -1, -1));
		jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(
				100, 330, -1, 20));
		jPanel1.add(jSeparator2,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 840,
						1050, 20));

		jTextArea2.setColumns(20);
		jTextArea2.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));
		jTextArea2.setRows(5);
		jScrollPane3.setViewportView(jTextArea2);

		jPanel1.add(jScrollPane3,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440,
						820, 100));

		jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
		jPanel1.add(jSeparator3,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 1050,
						-1));

		jTextField5.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 15));
		jTextField5.setText("\u6682\u65e0");
		jTextField5.setBorder(null);
		jPanel1.add(jTextField5,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, -1,
						-1));

		jLabel4.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 15));
		jLabel4.setText("\u79ef\u5206\uff1a");
		jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(
				30, 640, -1, -1));
		jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(
				100, 470, -1, 20));

		jTextArea3.setColumns(20);
		jTextArea3.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));
		jTextArea3.setRows(5);
		jScrollPane4.setViewportView(jTextArea3);

		jPanel1.add(jScrollPane4,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 580,
						820, 100));

		jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
		jPanel1.add(jSeparator4,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 422,
						1050, 140));

		jTextField6.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 15));
		jTextField6.setText("\u6682\u65e0");
		jTextField6.setBorder(null);
		jPanel1.add(jTextField6,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 730, -1,
						-1));

		jLabel6.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 15));
		jLabel6.setText("\u79ef\u5206\uff1a");
		jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(
				30, 780, -1, -1));
		jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(
				100, 610, -1, 20));

		jTextArea4.setColumns(20);
		jTextArea4.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));
		jTextArea4.setRows(5);
		jScrollPane5.setViewportView(jTextArea4);

		jPanel1.add(jScrollPane5,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 720,
						820, 100));

		jLabel8.setText("No.1");
		jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(
				980, 520, -1, -1));

		jLabel9.setText("No.2");
		jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(
				980, 660, -1, -1));

		jLabel10.setText("No.3");
		jPanel1.add(jLabel10,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 800, -1,
						-1));

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane2.setViewportView(jTextArea1);

		jPanel1.add(jScrollPane2,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250,
						810, 160));

		jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
		jPanel1.add(jSeparator5,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 560,
						1050, -1));

		jLabel11.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));
		jLabel11.setText("\u4e3b\u9898\u5185\u5bb9");
		jPanel1.add(jLabel11,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1,
						-1));

		jScrollPane1.setViewportView(jPanel1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1048,
				javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 722,
				javax.swing.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String text = this.jTextField1.getText();
		Desktop desktop = Desktop.getDesktop();
		try {
			desktop.browse(new URI("https://tieba.baidu.com/f?ie=utf-8&kw="
					+ text + "&fr=search"));
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (URISyntaxException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		try {
			//			jTextField3.setText(tip.getTipTitle());
			replay1 = ModelFactory.chaHuifu(ModelFactory.chaReplayIDMin(tip
					.getTipId()));
			replay3 = ModelFactory.chaHuifu(ModelFactory.chaReplayIDMax(tip
					.getTipId()));
			for (int i = ModelFactory.chaReplayIDMin(tip.getTipId()) + 1; i <= ModelFactory
					.chaReplayIDMax(tip.getTipId()); i++) {
				if (tip.getTipId() == ModelFactory.chaReplayTipID(i)) {
					replay2 = ModelFactory.chaHuifu(i);
				} else {
					replay2 = null;
				}
			}
			if (replay1 != null) {
				this.jTextField4.setText(ModelFactory.chaWritor(replay1
						.getUsId()));
				this.jLabel3.setText(String.valueOf(ModelFactory
						.chaJifen(replay1.getUsId())));
				this.jTextArea2.setText(replay1.getRepContent());
			}
			if (replay2 != null) {
				this.jTextField5.setText(ModelFactory.chaWritor(replay2
						.getUsId()));
				this.jLabel5.setText(String.valueOf(ModelFactory
						.chaJifen(replay2.getUsId())));
				this.jTextArea3.setText(replay2.getRepContent());
			}
			if (replay3 != null) {
				this.jTextField6.setText(ModelFactory.chaWritor(replay3
						.getUsId()));
				this.jLabel7.setText(String.valueOf(ModelFactory
						.chaJifen(replay3.getUsId())));
				this.jTextArea4.setText(replay3.getRepContent());
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		new Replay(tip, user).setVisible(true);
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		Users test = null;
		try {
			new MainBlank(user).setVisible(true);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Show_tie().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JScrollPane jScrollPane5;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JSeparator jSeparator2;
	private javax.swing.JSeparator jSeparator3;
	private javax.swing.JSeparator jSeparator4;
	private javax.swing.JSeparator jSeparator5;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextArea jTextArea2;
	private javax.swing.JTextArea jTextArea3;
	private javax.swing.JTextArea jTextArea4;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField5;
	private javax.swing.JTextField jTextField6;
	// End of variables declaration//GEN-END:variables

}